version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "06:00"
  - package-ecosystem: "cargo"
    directories:
      - "**/*"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "06:00"
